# Generated by Django 2.2.12 on 2020-05-26 20:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 20, 12, 5, 744856, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
